version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: daily
    assignees:
      - action-stars/dependabot-reviewers
