version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps
    labels:
      - dependency
    schedule:
      interval: weekly
