name: Dependabot Changelog Entry

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches: [main]

permissions: read-all

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/dependabot-changelog.yaml@d4724b3ea1635d9cc7064f5302cc411e54d52334 # v0.9.0
    permissions:
      contents: read
      id-token: write
