name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/release.yaml@0cddebf99588cb4c3e116dd5b7a7b0368757a435 # v0.3.0
    permissions:
      contents: write
