name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/release.yaml@13960f02548e9db632fc84c90f9c5c1e7cc1c068 # v0.2.1
    permissions:
      contents: write
