name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/release.yaml@436b5d8ebbc67151ec77f214d667d7393c3916af # v0.11.0
    permissions:
      contents: write
