name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/release.yaml@1c26bc5c41f95c692cae3373556ef4fb03e5daa6 # v0.3.1
    permissions:
      contents: write
