name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/release.yaml@086743338187563958bd5aaeca24c871753b21ca # v0.3.6
    permissions:
      contents: write
