name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/release.yaml@2b612bb18aa6eea1a4f5c8eb239a7d4bca5a1e93 # v0.2.0
    permissions:
      contents: write
