name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/validate-gh-workflows.yaml@2d9203f46a38f7678555356b64b1f8be63ae52cb # v0.5.0
    with:
      auto_doc: true
      markdownlint: true
      shellcheck: true
      yamlfmt: true
