name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/validate-gh-workflows.yaml@d04d3c1dc84deaeeba9930a3493cd30c034e1d69 # v0.5.1
    with:
      auto_doc: true
      markdownlint: true
      shellcheck: true
      yamlfmt: true
